version: 2
jobs:
  run_test:
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
    steps:
    - checkout
    - run: make setup
    - run: make test

  create_release_pr:
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "2a:b2:db:68:e4:f4:3e:76:db:c7:a9:77:33:a0:ec:02"
    - run:
        name: Install commands
        command: |
          # semver
          go get -u github.com/masa213f/semver/cmd/semver
          # hub
          curl -sSLf https://github.com/github/hub/releases/download/v2.12.7/hub-linux-amd64-2.8.3.tgz | \
          tar zxf - --strip-components=1 -C /tmp/ && \
          mv /tmp/bin/hub /usr/local/bin/hub
    - run:
        name: Confirm the release version
        command: |
          RELEASE_VERSION=$(semver ${CIRCLE_TAG} --json | jq -r ".version")
          echo "export RELEASE_VERSION=${RELEASE_VERSION}" >> ${BASH_ENV}
          echo "Version: ${RELEASE_VERSION}"
    - run:
        name: Set git configs
        command: |
          # memo: GTT_CONFIG_USER_NAME and GIT_CONFIG_USER_MAIL must be set by bash env.
          git config --global user.name "${GTT_CONFIG_USER_NAME}"
          git config --global user.email "${GIT_CONFIG_USER_MAIL}"
    - run:
        name: Update program version and commit
        command: |
          echo ${RELEASE_VERSION} > version.txt
          git add version.txt
          git commit -m "Bump version to ${RELEASE_VERSION}"
          git push
    - run:
        name: Create a pull request
        command: |
          hub pull-request --message="Bump version to ${RELEASE_VERSION}" --base=${CIRCLE_PROJECT_USERNAME}:master --head=${CIRCLE_PROJECT_USERNAME}:${CIRCLE_BRANCH}

  add_release_tag:
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "2a:b2:db:68:e4:f4:3e:76:db:c7:a9:77:33:a0:ec:02"
    - run:
        name: Set git configs
        command: |
          # memo: GTT_CONFIG_USER_NAME and GIT_CONFIG_USER_MAIL must be set by bash env.
          git config --global user.name "${GTT_CONFIG_USER_NAME}"
          git config --global user.email "${GIT_CONFIG_USER_MAIL}"
    - run:
        name: Add release tag
        command: |
          git tag $(cat version.txt)

  release_in_github:
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "2a:b2:db:68:e4:f4:3e:76:db:c7:a9:77:33:a0:ec:02"
    - run:
        name: Install commands
        command: |
          # hub
          curl -sSLf https://github.com/github/hub/releases/download/v2.12.7/hub-linux-amd64-2.8.3.tgz | \
          tar zxf - --strip-components=1 -C /tmp/ && \
          mv /tmp/bin/hub /usr/local/bin/hub
    - run:
        name: Build and output the program version
        command: |
          make build
          ./semver --version
          mv semver /tmp/release/semver-linux-amd64-v${RELEASE_VERSION}
    - run:
        name: Release as draft
        command: |
          set -x
          if semver -p "${RELEASE_VERSION}"; then
             PRE_OPT=-p
          fi
          hub release create -d ${PRE_OPT} -m v${RELEASE_VERSION} ${CIRCLE_TAG} -a ./semver-linux-amd64-v${RELEASE_VERSION}

workflows:
  version: 2
  develop:
    jobs:
    - run_test:
        filters:
          branches:
            only:
              - develop
              - /^feature/.*/
  release:
    jobs:
    - run_test:
        filters:
          branches:
            only: /.release-v.*/
    - create_release_pr:
        requires:
          - run_test
        filters:
          branches:
            only: /.release-v.*/
  master:
    jobs:
    - add_release_tag:
        filters:
          branches:
            only: master
    - release_in_github:
        filters:
          branches:
            only: master
